
export const SET_ACTIVE_PROJECT = 'SET_ACTIVE_PROJECT'
export const UNSET_ACTIVE_PROJECT = 'UNSET_ACTIVE_PROJECT'
export const SET_PROJECTS = 'SET_PROJECTS'
export const OPEN_PROJECT = 'OPEN_PROJECT'
export const CLOSE_PROJECT = 'CLOSE_PROJECT'
