export const SET_VISUALIZATIONS = 'SET_VISUALIZATIONS'
export const SET_CURRENT_VISUALIZATION = 'SET_CURRENT_VISUALIZATION'
export const ADD_VISUALIZATION = 'ADD_VISUALIZATION'
export const UPDATE_VISUALIZATION = 'UPDATE_VISUALIZATION'
